### ISSUE TITLE
API 명세 작성

### ISSUE THREAD

**Issue by winocreative** [pknu-wap/2022_2_WAP_APP_TEAM1#39]
## 📑 작업 사항 
swagger 라이브러리를 이용해 API 명세 작성

## To-do
- [x] swagger 라이브러리 추가 및 기본 설정
- [ ] api 명세서 주석으로 작성

# #✔️ 기타사항

controller과 model 폴더 구조 변경

**Comment by jeongjaino** [comment]
재완쿤 화이팅,,

**Comment by winocreative** [comment]
swagger 안쓰고 직접 노션에 API 정리하기로 함..

**Comment by winocreative** [comment]
swagger 안쓰고 노션에 정리하기로 함..
